### ISSUE TITLE
Pictures ?

### ISSUE THREAD

**Issue by Dreadox** [kata-gatame/Blaster#1]
Any pictures of it ?

**Comment by kata-gatame** [comment]
As of right now, there really isn't a ton to show off. I have been working on implementing the base networking functionality and getting all the animations and such to play correctly on each machine (server/client). Below is a quick example of what I have completed so far.

There is still a lot of work to be done.

https://user-images.githubusercontent.com/57286237/171040051-0112a7b3-a7d2-43ec-92be-a987099040ef.mp4
